services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: fastapi-app
    command: poetry run uvicorn main:app --host 0.0.0.0 --port 8000
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    networks:
      - app-network

  redis:
    image: redis:alpine
    container_name: redis
    command: redis-server
    ports:
      - "6379:6379"
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend-app
    environment:
      - FRONTEND_ENV=production
      - VITE_BACKEND_API_URL=http://backend:8000  # Use o nome do serviço no Docker Compose
      - VITE_PWD_SIGNUP_ENABLED=true
      - VITE_GA_TRACKING_ID=your-ga-tracking-id
    ports:
      - "5173:80"
    depends_on:
      - backend
    networks:
      - app-network

  mobile:
    build:
      context: ./mobile
      dockerfile: Dockerfile
    container_name: mobile-app
    command: npm start
    volumes:
      - ./mobile:/app
    ports:
      - "19000:19000" # Porta para o Expo DevTools
      - "19001:19001" # Porta para o Expo (Metro Bundler)
      - "19002:19002" # Porta para o Expo Web
    environment:
      # Captura automaticamente o IP do host
      - BACKEND_API_URL=http://$(ip route get 1 | awk '{print $7; exit}'):8000
    depends_on:
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
