services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fastapi-app
    command: poetry run uvicorn main:app --host 0.0.0.0 --port 8000
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    networks:
      - app-network

  redis:
    image: redis:alpine
    container_name: redis
    command: redis-server
    ports:
      - "6379:6379"
    networks:
      - app-network

  frontend:
    build:
      context: ../frontend
      dockerfile: Dockerfile
    container_name: frontend-app
    environment:
      - FRONTEND_ENV=production
      - VITE_BACKEND_API_URL=http://backend:8000  # Use o nome do serviço no Docker Compose
      - VITE_PWD_SIGNUP_ENABLED=true
      - VITE_GA_TRACKING_ID=your-ga-tracking-id
    ports:
      - "5173:80"
    depends_on:
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
